language: python
python:
  - "3.6"
before_install:
  - pip install pycodestyle codecov
  - python3 setup.py install
script:
  - pycodestyle --exclude=venv --ignore=E501 .
  - pytest
after_success:
  - codecov